// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mocks/mock_email_sender.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailSender is a mock of EmailSender interface.
type MockEmailSender struct {
	ctrl     *gomock.Controller
	recorder *MockEmailSenderMockRecorder
	isgomock struct{}
}

// MockEmailSenderMockRecorder is the mock recorder for MockEmailSender.
type MockEmailSenderMockRecorder struct {
	mock *MockEmailSender
}

// NewMockEmailSender creates a new mock instance.
func NewMockEmailSender(ctrl *gomock.Controller) *MockEmailSender {
	mock := &MockEmailSender{ctrl: ctrl}
	mock.recorder = &MockEmailSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailSender) EXPECT() *MockEmailSenderMockRecorder {
	return m.recorder
}

// SendResetNotification mocks base method.
func (m *MockEmailSender) SendResetNotification(email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResetNotification", email)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResetNotification indicates an expected call of SendResetNotification.
func (mr *MockEmailSenderMockRecorder) SendResetNotification(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResetNotification", reflect.TypeOf((*MockEmailSender)(nil).SendResetNotification), email)
}

// SendResetPassword mocks base method.
func (m *MockEmailSender) SendResetPassword(email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendResetPassword", email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendResetPassword indicates an expected call of SendResetPassword.
func (mr *MockEmailSenderMockRecorder) SendResetPassword(email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendResetPassword", reflect.TypeOf((*MockEmailSender)(nil).SendResetPassword), email, token)
}

// SendShareNotification mocks base method.
func (m *MockEmailSender) SendShareNotification(email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendShareNotification", email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendShareNotification indicates an expected call of SendShareNotification.
func (mr *MockEmailSenderMockRecorder) SendShareNotification(email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendShareNotification", reflect.TypeOf((*MockEmailSender)(nil).SendShareNotification), email, token)
}

// SendVerificationToken mocks base method.
func (m *MockEmailSender) SendVerificationToken(email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationToken", email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationToken indicates an expected call of SendVerificationToken.
func (mr *MockEmailSenderMockRecorder) SendVerificationToken(email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationToken", reflect.TypeOf((*MockEmailSender)(nil).SendVerificationToken), email, token)
}
