// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/labib0x9/ffgif/internal/port/queue (interfaces: Queue)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_queue.go github.com/labib0x9/ffgif/internal/port/queue Queue
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	queue "github.com/labib0x9/ffgif/internal/port/queue"
	amqp091 "github.com/rabbitmq/amqp091-go"
	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockQueue) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockQueueMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockQueue)(nil).Close))
}

// CloseConsumerChannel mocks base method.
func (m *MockQueue) CloseConsumerChannel(name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseConsumerChannel", name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseConsumerChannel indicates an expected call of CloseConsumerChannel.
func (mr *MockQueueMockRecorder) CloseConsumerChannel(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseConsumerChannel", reflect.TypeOf((*MockQueue)(nil).CloseConsumerChannel), name)
}

// ConsumeEmail mocks base method.
func (m *MockQueue) ConsumeEmail(ctx context.Context, name string, concurrency int) (<-chan amqp091.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeEmail", ctx, name, concurrency)
	ret0, _ := ret[0].(<-chan amqp091.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeEmail indicates an expected call of ConsumeEmail.
func (mr *MockQueueMockRecorder) ConsumeEmail(ctx, name, concurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeEmail", reflect.TypeOf((*MockQueue)(nil).ConsumeEmail), ctx, name, concurrency)
}

// ConsumeRawVideo mocks base method.
func (m *MockQueue) ConsumeRawVideo(ctx context.Context, name string, concurrency int) (<-chan amqp091.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeRawVideo", ctx, name, concurrency)
	ret0, _ := ret[0].(<-chan amqp091.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeRawVideo indicates an expected call of ConsumeRawVideo.
func (mr *MockQueueMockRecorder) ConsumeRawVideo(ctx, name, concurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeRawVideo", reflect.TypeOf((*MockQueue)(nil).ConsumeRawVideo), ctx, name, concurrency)
}

// ConsumeSave mocks base method.
func (m *MockQueue) ConsumeSave(ctx context.Context, name string, concurrency int) (<-chan amqp091.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeSave", ctx, name, concurrency)
	ret0, _ := ret[0].(<-chan amqp091.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeSave indicates an expected call of ConsumeSave.
func (mr *MockQueueMockRecorder) ConsumeSave(ctx, name, concurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeSave", reflect.TypeOf((*MockQueue)(nil).ConsumeSave), ctx, name, concurrency)
}

// ConsumeVideo mocks base method.
func (m *MockQueue) ConsumeVideo(ctx context.Context, name string, concurrency int) (<-chan amqp091.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeVideo", ctx, name, concurrency)
	ret0, _ := ret[0].(<-chan amqp091.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeVideo indicates an expected call of ConsumeVideo.
func (mr *MockQueueMockRecorder) ConsumeVideo(ctx, name, concurrency any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeVideo", reflect.TypeOf((*MockQueue)(nil).ConsumeVideo), ctx, name, concurrency)
}

// PublishEmail mocks base method.
func (m *MockQueue) PublishEmail(ctx context.Context, msg queue.EmailMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishEmail", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishEmail indicates an expected call of PublishEmail.
func (mr *MockQueueMockRecorder) PublishEmail(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishEmail", reflect.TypeOf((*MockQueue)(nil).PublishEmail), ctx, msg)
}

// PublishRetrySaveVideo mocks base method.
func (m *MockQueue) PublishRetrySaveVideo(ctx context.Context, msg queue.SaveVideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishRetrySaveVideo", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishRetrySaveVideo indicates an expected call of PublishRetrySaveVideo.
func (mr *MockQueueMockRecorder) PublishRetrySaveVideo(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishRetrySaveVideo", reflect.TypeOf((*MockQueue)(nil).PublishRetrySaveVideo), ctx, msg)
}

// PublishSaveVideo mocks base method.
func (m *MockQueue) PublishSaveVideo(ctx context.Context, msg queue.SaveVideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishSaveVideo", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishSaveVideo indicates an expected call of PublishSaveVideo.
func (mr *MockQueueMockRecorder) PublishSaveVideo(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishSaveVideo", reflect.TypeOf((*MockQueue)(nil).PublishSaveVideo), ctx, msg)
}

// PublishVideo mocks base method.
func (m *MockQueue) PublishVideo(ctx context.Context, msg queue.VideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishVideo", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishVideo indicates an expected call of PublishVideo.
func (mr *MockQueueMockRecorder) PublishVideo(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishVideo", reflect.TypeOf((*MockQueue)(nil).PublishVideo), ctx, msg)
}
