// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_media_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	media "github.com/labib0x9/ffgif/internal/app/media"
	media0 "github.com/labib0x9/ffgif/internal/domain/media"
	queue "github.com/labib0x9/ffgif/internal/port/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ConversionStatus mocks base method.
func (m *MockService) ConversionStatus(ctx context.Context, jobId string) (*media.StatusResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConversionStatus", ctx, jobId)
	ret0, _ := ret[0].(*media.StatusResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConversionStatus indicates an expected call of ConversionStatus.
func (mr *MockServiceMockRecorder) ConversionStatus(ctx, jobId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConversionStatus", reflect.TypeOf((*MockService)(nil).ConversionStatus), ctx, jobId)
}

// Convert mocks base method.
func (m *MockService) Convert(ctx context.Context, userId, key string, start, end float32, fps, width int, loop bool) (*media.ConvertResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Convert", ctx, userId, key, start, end, fps, width, loop)
	ret0, _ := ret[0].(*media.ConvertResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Convert indicates an expected call of Convert.
func (mr *MockServiceMockRecorder) Convert(ctx, userId, key, start, end, fps, width, loop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Convert", reflect.TypeOf((*MockService)(nil).Convert), ctx, userId, key, start, end, fps, width, loop)
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, userId, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userId, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, userId, key)
}

// Download mocks base method.
func (m *MockService) Download(ctx context.Context, userId, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, userId, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockServiceMockRecorder) Download(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockService)(nil).Download), ctx, userId, key)
}

// GetByKey mocks base method.
func (m *MockService) GetByKey(ctx context.Context, userId, key string) (*media0.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, userId, key)
	ret0, _ := ret[0].(*media0.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockServiceMockRecorder) GetByKey(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockService)(nil).GetByKey), ctx, userId, key)
}

// GetGifThumbnail mocks base method.
func (m *MockService) GetGifThumbnail(ctx context.Context, userId, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGifThumbnail", ctx, userId, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGifThumbnail indicates an expected call of GetGifThumbnail.
func (mr *MockServiceMockRecorder) GetGifThumbnail(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGifThumbnail", reflect.TypeOf((*MockService)(nil).GetGifThumbnail), ctx, userId, key)
}

// GetGifs mocks base method.
func (m *MockService) GetGifs(ctx context.Context, userId, filter string) (*media.GifResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGifs", ctx, userId, filter)
	ret0, _ := ret[0].(*media.GifResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGifs indicates an expected call of GetGifs.
func (mr *MockServiceMockRecorder) GetGifs(ctx, userId, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGifs", reflect.TypeOf((*MockService)(nil).GetGifs), ctx, userId, filter)
}

// GetRecents mocks base method.
func (m *MockService) GetRecents(ctx context.Context, userId string) ([]media0.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecents", ctx, userId)
	ret0, _ := ret[0].([]media0.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecents indicates an expected call of GetRecents.
func (mr *MockServiceMockRecorder) GetRecents(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecents", reflect.TypeOf((*MockService)(nil).GetRecents), ctx, userId)
}

// LastVideo mocks base method.
func (m *MockService) LastVideo(ctx context.Context, userId string) (media0.LastUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastVideo", ctx, userId)
	ret0, _ := ret[0].(media0.LastUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastVideo indicates an expected call of LastVideo.
func (mr *MockServiceMockRecorder) LastVideo(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastVideo", reflect.TypeOf((*MockService)(nil).LastVideo), ctx, userId)
}

// Process mocks base method.
func (m *MockService) Process(ctx context.Context, msg queue.VideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockServiceMockRecorder) Process(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockService)(nil).Process), ctx, msg)
}

// ProcessAndSave mocks base method.
func (m *MockService) ProcessAndSave(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessAndSave", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessAndSave indicates an expected call of ProcessAndSave.
func (mr *MockServiceMockRecorder) ProcessAndSave(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessAndSave", reflect.TypeOf((*MockService)(nil).ProcessAndSave), ctx, key)
}

// Save mocks base method.
func (m *MockService) Save(ctx context.Context, userId, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, userId, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockServiceMockRecorder) Save(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockService)(nil).Save), ctx, userId, key)
}

// SaveMetadata mocks base method.
func (m *MockService) SaveMetadata(ctx context.Context, msg queue.SaveVideoMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMetadata", ctx, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMetadata indicates an expected call of SaveMetadata.
func (mr *MockServiceMockRecorder) SaveMetadata(ctx, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMetadata", reflect.TypeOf((*MockService)(nil).SaveMetadata), ctx, msg)
}

// Status mocks base method.
func (m *MockService) Status(ctx context.Context, userId, key string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, userId, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Status indicates an expected call of Status.
func (mr *MockServiceMockRecorder) Status(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockService)(nil).Status), ctx, userId, key)
}

// Stream mocks base method.
func (m *MockService) Stream(ctx context.Context, userId, key string) (*media0.StreamResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stream", ctx, userId, key)
	ret0, _ := ret[0].(*media0.StreamResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stream indicates an expected call of Stream.
func (mr *MockServiceMockRecorder) Stream(ctx, userId, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stream", reflect.TypeOf((*MockService)(nil).Stream), ctx, userId, key)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, userId, key string, _gif media0.GifUpdateRequest, lastUpdatedAt string) (*media0.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userId, key, _gif, lastUpdatedAt)
	ret0, _ := ret[0].(*media0.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, userId, key, _gif, lastUpdatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, userId, key, _gif, lastUpdatedAt)
}

// UpdateUploadingStatus mocks base method.
func (m *MockService) UpdateUploadingStatus(ctx context.Context, key, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUploadingStatus", ctx, key, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUploadingStatus indicates an expected call of UpdateUploadingStatus.
func (mr *MockServiceMockRecorder) UpdateUploadingStatus(ctx, key, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUploadingStatus", reflect.TypeOf((*MockService)(nil).UpdateUploadingStatus), ctx, key, status)
}

// Upload mocks base method.
func (m *MockService) Upload(rctx context.Context, filename, userId string) (*media0.UploadResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", rctx, filename, userId)
	ret0, _ := ret[0].(*media0.UploadResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockServiceMockRecorder) Upload(rctx, filename, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockService)(nil).Upload), rctx, filename, userId)
}
