// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/labib0x9/ffgif/internal/app/auth (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_auth_service.go github.com/labib0x9/ffgif/internal/app/auth Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/labib0x9/ffgif/internal/app/auth"
	jwt "github.com/labib0x9/ffgif/pkg/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ForgotPassword mocks base method.
func (m *MockService) ForgotPassword(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForgotPassword", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ForgotPassword indicates an expected call of ForgotPassword.
func (mr *MockServiceMockRecorder) ForgotPassword(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForgotPassword", reflect.TypeOf((*MockService)(nil).ForgotPassword), ctx, email)
}

// Login mocks base method.
func (m *MockService) Login(ctx context.Context, email, password string) (*auth.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*auth.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), ctx, email, password)
}

// Logout mocks base method.
func (m *MockService) Logout(ctx context.Context, arg1 string, claims jwt.Payload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, arg1, claims)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockServiceMockRecorder) Logout(ctx, arg1, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockService)(nil).Logout), ctx, arg1, claims)
}

// ResendVerify mocks base method.
func (m *MockService) ResendVerify(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResendVerify", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResendVerify indicates an expected call of ResendVerify.
func (mr *MockServiceMockRecorder) ResendVerify(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResendVerify", reflect.TypeOf((*MockService)(nil).ResendVerify), ctx, email)
}

// ResetPasswordGet mocks base method.
func (m *MockService) ResetPasswordGet(ctx context.Context, token string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordGet", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResetPasswordGet indicates an expected call of ResetPasswordGet.
func (mr *MockServiceMockRecorder) ResetPasswordGet(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordGet", reflect.TypeOf((*MockService)(nil).ResetPasswordGet), ctx, token)
}

// ResetPasswordPost mocks base method.
func (m *MockService) ResetPasswordPost(ctx context.Context, token, pass, confirmPass string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResetPasswordPost", ctx, token, pass, confirmPass)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResetPasswordPost indicates an expected call of ResetPasswordPost.
func (mr *MockServiceMockRecorder) ResetPasswordPost(ctx, token, pass, confirmPass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResetPasswordPost", reflect.TypeOf((*MockService)(nil).ResetPasswordPost), ctx, token, pass, confirmPass)
}

// Signup mocks base method.
func (m *MockService) Signup(ctx context.Context, email, username, fullname, password string) (*auth.SignupResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signup", ctx, email, username, fullname, password)
	ret0, _ := ret[0].(*auth.SignupResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signup indicates an expected call of Signup.
func (mr *MockServiceMockRecorder) Signup(ctx, email, username, fullname, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signup", reflect.TypeOf((*MockService)(nil).Signup), ctx, email, username, fullname, password)
}

// Verify mocks base method.
func (m *MockService) Verify(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockServiceMockRecorder) Verify(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockService)(nil).Verify), ctx, token)
}
