package auth

const (
	AUTH_INVALID_CREDENTIALS  = "AUTH_INVALID_CREDENTIALS"
	AUTH_USER_NOT_VERIFIED    = "AUTH_USER_NOT_VERIFIED"
	AUTH_USER_EXISTS          = "AUTH_USER_EXISTS"
	AUTH_USER_NOT_FOUND       = "AUTH_USER_NOT_FOUND"
	AUTH_RESET_TOKEN_INVALID  = "AUTH_RESET_TOKEN_INVALID"
	AUTH_VERIFY_TOKEN_INVALID = "AUTH_VERIFY_TOKEN_INVALID"
)
