// Code generated by MockGen. DO NOT EDIT.
// Source: quota.go
//
// Generated by this command:
//
//	mockgen -source=quota.go -destination=mocks/mock_quota_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/labib0x9/ffgif/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockQuotaRepository is a mock of QuotaRepository interface.
type MockQuotaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuotaRepositoryMockRecorder
	isgomock struct{}
}

// MockQuotaRepositoryMockRecorder is the mock recorder for MockQuotaRepository.
type MockQuotaRepositoryMockRecorder struct {
	mock *MockQuotaRepository
}

// NewMockQuotaRepository creates a new mock instance.
func NewMockQuotaRepository(ctrl *gomock.Controller) *MockQuotaRepository {
	mock := &MockQuotaRepository{ctrl: ctrl}
	mock.recorder = &MockQuotaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuotaRepository) EXPECT() *MockQuotaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuotaRepository) Create(ctx context.Context, quota user.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quota)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuotaRepositoryMockRecorder) Create(ctx, quota any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuotaRepository)(nil).Create), ctx, quota)
}

// GetById mocks base method.
func (m *MockQuotaRepository) GetById(ctx context.Context, userId string) (*user.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, userId)
	ret0, _ := ret[0].(*user.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockQuotaRepositoryMockRecorder) GetById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockQuotaRepository)(nil).GetById), ctx, userId)
}

// IncrementUsage mocks base method.
func (m *MockQuotaRepository) IncrementUsage(ctx context.Context, userId string, addBytes, addGifCount int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementUsage", ctx, userId, addBytes, addGifCount)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementUsage indicates an expected call of IncrementUsage.
func (mr *MockQuotaRepositoryMockRecorder) IncrementUsage(ctx, userId, addBytes, addGifCount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementUsage", reflect.TypeOf((*MockQuotaRepository)(nil).IncrementUsage), ctx, userId, addBytes, addGifCount)
}

// MockAnonQuotaRepository is a mock of AnonQuotaRepository interface.
type MockAnonQuotaRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnonQuotaRepositoryMockRecorder
	isgomock struct{}
}

// MockAnonQuotaRepositoryMockRecorder is the mock recorder for MockAnonQuotaRepository.
type MockAnonQuotaRepositoryMockRecorder struct {
	mock *MockAnonQuotaRepository
}

// NewMockAnonQuotaRepository creates a new mock instance.
func NewMockAnonQuotaRepository(ctrl *gomock.Controller) *MockAnonQuotaRepository {
	mock := &MockAnonQuotaRepository{ctrl: ctrl}
	mock.recorder = &MockAnonQuotaRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonQuotaRepository) EXPECT() *MockAnonQuotaRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAnonQuotaRepository) Create(ctx context.Context, quota user.Quota) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, quota)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAnonQuotaRepositoryMockRecorder) Create(ctx, quota any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAnonQuotaRepository)(nil).Create), ctx, quota)
}

// GetById mocks base method.
func (m *MockAnonQuotaRepository) GetById(ctx context.Context, userId string) (*user.Quota, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, userId)
	ret0, _ := ret[0].(*user.Quota)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockAnonQuotaRepositoryMockRecorder) GetById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockAnonQuotaRepository)(nil).GetById), ctx, userId)
}
