// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/labib0x9/ffgif/internal/domain/user (interfaces: UserRepository,AnonUserRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_user_repo.go github.com/labib0x9/ffgif/internal/domain/user UserRepository,AnonUserRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/labib0x9/ffgif/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockUserRepository) ChangePassword(ctx context.Context, userId, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userId, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockUserRepositoryMockRecorder) ChangePassword(ctx, userId, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockUserRepository)(nil).ChangePassword), ctx, userId, hash)
}

// GetProfile mocks base method.
func (m *MockUserRepository) GetProfile(ctx context.Context, userId string, forUpdate bool) (user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userId, forUpdate)
	ret0, _ := ret[0].(user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockUserRepositoryMockRecorder) GetProfile(ctx, userId, forUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockUserRepository)(nil).GetProfile), ctx, userId, forUpdate)
}

// SetProfile mocks base method.
func (m *MockUserRepository) SetProfile(ctx context.Context, profile user.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProfile indicates an expected call of SetProfile.
func (mr *MockUserRepositoryMockRecorder) SetProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProfile", reflect.TypeOf((*MockUserRepository)(nil).SetProfile), ctx, profile)
}

// UpdateProfile mocks base method.
func (m *MockUserRepository) UpdateProfile(ctx context.Context, req user.ProfileUpdateRequest, userId string) (user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, req, userId)
	ret0, _ := ret[0].(user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockUserRepositoryMockRecorder) UpdateProfile(ctx, req, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockUserRepository)(nil).UpdateProfile), ctx, req, userId)
}

// MockAnonUserRepository is a mock of AnonUserRepository interface.
type MockAnonUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAnonUserRepositoryMockRecorder
	isgomock struct{}
}

// MockAnonUserRepositoryMockRecorder is the mock recorder for MockAnonUserRepository.
type MockAnonUserRepositoryMockRecorder struct {
	mock *MockAnonUserRepository
}

// NewMockAnonUserRepository creates a new mock instance.
func NewMockAnonUserRepository(ctrl *gomock.Controller) *MockAnonUserRepository {
	mock := &MockAnonUserRepository{ctrl: ctrl}
	mock.recorder = &MockAnonUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnonUserRepository) EXPECT() *MockAnonUserRepositoryMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockAnonUserRepository) GetProfile(ctx context.Context, id string) (user.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, id)
	ret0, _ := ret[0].(user.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockAnonUserRepositoryMockRecorder) GetProfile(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockAnonUserRepository)(nil).GetProfile), ctx, id)
}

// SetProfile mocks base method.
func (m *MockAnonUserRepository) SetProfile(ctx context.Context, profile user.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetProfile", ctx, profile)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetProfile indicates an expected call of SetProfile.
func (mr *MockAnonUserRepositoryMockRecorder) SetProfile(ctx, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProfile", reflect.TypeOf((*MockAnonUserRepository)(nil).SetProfile), ctx, profile)
}
