// Code generated by MockGen. DO NOT EDIT.
// Source: verifier.go
//
// Generated by this command:
//
//	mockgen -source=verifier.go -destination=mocks/mock_verifier_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	auth "github.com/labib0x9/ffgif/internal/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifierRepository is a mock of VerifierRepository interface.
type MockVerifierRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierRepositoryMockRecorder
	isgomock struct{}
}

// MockVerifierRepositoryMockRecorder is the mock recorder for MockVerifierRepository.
type MockVerifierRepositoryMockRecorder struct {
	mock *MockVerifierRepository
}

// NewMockVerifierRepository creates a new mock instance.
func NewMockVerifierRepository(ctrl *gomock.Controller) *MockVerifierRepository {
	mock := &MockVerifierRepository{ctrl: ctrl}
	mock.recorder = &MockVerifierRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifierRepository) EXPECT() *MockVerifierRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVerifierRepository) Create(ctx context.Context, verifier auth.Verifier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, verifier)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerifierRepositoryMockRecorder) Create(ctx, verifier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerifierRepository)(nil).Create), ctx, verifier)
}

// Delete mocks base method.
func (m *MockVerifierRepository) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVerifierRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVerifierRepository)(nil).Delete), ctx, id)
}

// GetByHash mocks base method.
func (m *MockVerifierRepository) GetByHash(ctx context.Context, tokenHash string) (auth.Verifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByHash", ctx, tokenHash)
	ret0, _ := ret[0].(auth.Verifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByHash indicates an expected call of GetByHash.
func (mr *MockVerifierRepositoryMockRecorder) GetByHash(ctx, tokenHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByHash", reflect.TypeOf((*MockVerifierRepository)(nil).GetByHash), ctx, tokenHash)
}

// GetById mocks base method.
func (m *MockVerifierRepository) GetById(ctx context.Context, userId uuid.UUID) (auth.Verifier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, userId)
	ret0, _ := ret[0].(auth.Verifier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockVerifierRepositoryMockRecorder) GetById(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockVerifierRepository)(nil).GetById), ctx, userId)
}
