// Code generated by MockGen. DO NOT EDIT.
// Source: reseter.go
//
// Generated by this command:
//
//	mockgen -source=reseter.go -destination=mocks/mock_reseter_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	auth "github.com/labib0x9/ffgif/internal/domain/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockReseterRepository is a mock of ReseterRepository interface.
type MockReseterRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReseterRepositoryMockRecorder
	isgomock struct{}
}

// MockReseterRepositoryMockRecorder is the mock recorder for MockReseterRepository.
type MockReseterRepositoryMockRecorder struct {
	mock *MockReseterRepository
}

// NewMockReseterRepository creates a new mock instance.
func NewMockReseterRepository(ctrl *gomock.Controller) *MockReseterRepository {
	mock := &MockReseterRepository{ctrl: ctrl}
	mock.recorder = &MockReseterRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReseterRepository) EXPECT() *MockReseterRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockReseterRepository) Create(ctx context.Context, reseter auth.Reseter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reseter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockReseterRepositoryMockRecorder) Create(ctx, reseter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockReseterRepository)(nil).Create), ctx, reseter)
}

// DeleteById mocks base method.
func (m *MockReseterRepository) DeleteById(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteById indicates an expected call of DeleteById.
func (mr *MockReseterRepositoryMockRecorder) DeleteById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteById", reflect.TypeOf((*MockReseterRepository)(nil).DeleteById), ctx, id)
}

// GetById mocks base method.
func (m *MockReseterRepository) GetById(ctx context.Context, id uuid.UUID) (auth.Reseter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(auth.Reseter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockReseterRepositoryMockRecorder) GetById(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockReseterRepository)(nil).GetById), ctx, id)
}

// GetByToken mocks base method.
func (m *MockReseterRepository) GetByToken(ctx context.Context, token string) (auth.Reseter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(auth.Reseter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockReseterRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockReseterRepository)(nil).GetByToken), ctx, token)
}

// Update mocks base method.
func (m *MockReseterRepository) Update(ctx context.Context, reseter auth.Reseter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, reseter)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockReseterRepositoryMockRecorder) Update(ctx, reseter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockReseterRepository)(nil).Update), ctx, reseter)
}
