// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/labib0x9/ffgif/internal/domain/media (interfaces: GifRepository)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_gif_repo.go github.com/labib0x9/ffgif/internal/domain/media GifRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	media "github.com/labib0x9/ffgif/internal/domain/media"
	gomock "go.uber.org/mock/gomock"
)

// MockGifRepository is a mock of GifRepository interface.
type MockGifRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGifRepositoryMockRecorder
	isgomock struct{}
}

// MockGifRepositoryMockRecorder is the mock recorder for MockGifRepository.
type MockGifRepositoryMockRecorder struct {
	mock *MockGifRepository
}

// NewMockGifRepository creates a new mock instance.
func NewMockGifRepository(ctrl *gomock.Controller) *MockGifRepository {
	mock := &MockGifRepository{ctrl: ctrl}
	mock.recorder = &MockGifRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGifRepository) EXPECT() *MockGifRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockGifRepository) Create(ctx context.Context, gif media.Gif) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockGifRepositoryMockRecorder) Create(ctx, gif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGifRepository)(nil).Create), ctx, gif)
}

// Delete mocks base method.
func (m *MockGifRepository) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockGifRepositoryMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGifRepository)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockGifRepository) Get(ctx context.Context, user_id, status string) ([]media.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, user_id, status)
	ret0, _ := ret[0].([]media.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGifRepositoryMockRecorder) Get(ctx, user_id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGifRepository)(nil).Get), ctx, user_id, status)
}

// GetByKey mocks base method.
func (m *MockGifRepository) GetByKey(ctx context.Context, key string, forUpdate bool) (media.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByKey", ctx, key, forUpdate)
	ret0, _ := ret[0].(media.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByKey indicates an expected call of GetByKey.
func (mr *MockGifRepositoryMockRecorder) GetByKey(ctx, key, forUpdate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByKey", reflect.TypeOf((*MockGifRepository)(nil).GetByKey), ctx, key, forUpdate)
}

// GetOwner mocks base method.
func (m *MockGifRepository) GetOwner(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwner", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwner indicates an expected call of GetOwner.
func (mr *MockGifRepositoryMockRecorder) GetOwner(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwner", reflect.TypeOf((*MockGifRepository)(nil).GetOwner), ctx, key)
}

// GetRecents mocks base method.
func (m *MockGifRepository) GetRecents(ctx context.Context, user_id string) ([]media.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecents", ctx, user_id)
	ret0, _ := ret[0].([]media.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecents indicates an expected call of GetRecents.
func (mr *MockGifRepositoryMockRecorder) GetRecents(ctx, user_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecents", reflect.TypeOf((*MockGifRepository)(nil).GetRecents), ctx, user_id)
}

// SaveRecent mocks base method.
func (m *MockGifRepository) SaveRecent(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRecent", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRecent indicates an expected call of SaveRecent.
func (mr *MockGifRepositoryMockRecorder) SaveRecent(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRecent", reflect.TypeOf((*MockGifRepository)(nil).SaveRecent), ctx, key)
}

// Update mocks base method.
func (m *MockGifRepository) Update(ctx context.Context, key string, req media.GifUpdateRequest) (media.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, key, req)
	ret0, _ := ret[0].(media.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGifRepositoryMockRecorder) Update(ctx, key, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGifRepository)(nil).Update), ctx, key, req)
}
