// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source=storage.go -destination=mocks/mock_storage_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	url "net/url"
	reflect "reflect"
	time "time"

	media "github.com/labib0x9/ffgif/internal/domain/media"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepository is a mock of StorageRepository interface.
type MockStorageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepositoryMockRecorder
	isgomock struct{}
}

// MockStorageRepositoryMockRecorder is the mock recorder for MockStorageRepository.
type MockStorageRepositoryMockRecorder struct {
	mock *MockStorageRepository
}

// NewMockStorageRepository creates a new mock instance.
func NewMockStorageRepository(ctrl *gomock.Controller) *MockStorageRepository {
	mock := &MockStorageRepository{ctrl: ctrl}
	mock.recorder = &MockStorageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepository) EXPECT() *MockStorageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStorageRepository) Create(ctx context.Context, key string, expirey time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, key, expirey)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockStorageRepositoryMockRecorder) Create(ctx, key, expirey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStorageRepository)(nil).Create), ctx, key, expirey)
}

// Download mocks base method.
func (m *MockStorageRepository) Download(ctx context.Context, key string, expirey time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, key, expirey)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockStorageRepositoryMockRecorder) Download(ctx, key, expirey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStorageRepository)(nil).Download), ctx, key, expirey)
}

// DownloadLocal mocks base method.
func (m *MockStorageRepository) DownloadLocal(ctx context.Context, key, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLocal", ctx, key, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadLocal indicates an expected call of DownloadLocal.
func (mr *MockStorageRepositoryMockRecorder) DownloadLocal(ctx, key, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLocal", reflect.TypeOf((*MockStorageRepository)(nil).DownloadLocal), ctx, key, destPath)
}

// DownloadLocalRawVideo mocks base method.
func (m *MockStorageRepository) DownloadLocalRawVideo(ctx context.Context, key, destPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadLocalRawVideo", ctx, key, destPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// DownloadLocalRawVideo indicates an expected call of DownloadLocalRawVideo.
func (mr *MockStorageRepositoryMockRecorder) DownloadLocalRawVideo(ctx, key, destPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadLocalRawVideo", reflect.TypeOf((*MockStorageRepository)(nil).DownloadLocalRawVideo), ctx, key, destPath)
}

// GetStreamURL mocks base method.
func (m *MockStorageRepository) GetStreamURL(ctx context.Context, key string, expiry time.Duration) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamURL", ctx, key, expiry)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamURL indicates an expected call of GetStreamURL.
func (mr *MockStorageRepositoryMockRecorder) GetStreamURL(ctx, key, expiry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamURL", reflect.TypeOf((*MockStorageRepository)(nil).GetStreamURL), ctx, key, expiry)
}

// GetThumbnailURL mocks base method.
func (m *MockStorageRepository) GetThumbnailURL(ctx context.Context, key string) (*url.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetThumbnailURL", ctx, key)
	ret0, _ := ret[0].(*url.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetThumbnailURL indicates an expected call of GetThumbnailURL.
func (mr *MockStorageRepositoryMockRecorder) GetThumbnailURL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetThumbnailURL", reflect.TypeOf((*MockStorageRepository)(nil).GetThumbnailURL), ctx, key)
}

// IsExists mocks base method.
func (m *MockStorageRepository) IsExists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsExists indicates an expected call of IsExists.
func (mr *MockStorageRepositoryMockRecorder) IsExists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExists", reflect.TypeOf((*MockStorageRepository)(nil).IsExists), ctx, key)
}

// Status mocks base method.
func (m *MockStorageRepository) Status(ctx context.Context, key string) (media.Info, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, key)
	ret0, _ := ret[0].(media.Info)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockStorageRepositoryMockRecorder) Status(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockStorageRepository)(nil).Status), ctx, key)
}

// Upload mocks base method.
func (m *MockStorageRepository) Upload(ctx context.Context, key, filePath, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, filePath, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockStorageRepositoryMockRecorder) Upload(ctx, key, filePath, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockStorageRepository)(nil).Upload), ctx, key, filePath, contentType)
}
