// Code generated by MockGen. DO NOT EDIT.
// Source: upload.go
//
// Generated by this command:
//
//	mockgen -source=upload.go -destination=mocks/mock_last_video_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	media "github.com/labib0x9/ffgif/internal/domain/media"
	gomock "go.uber.org/mock/gomock"
)

// MockLastVideoRepository is a mock of LastVideoRepository interface.
type MockLastVideoRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLastVideoRepositoryMockRecorder
	isgomock struct{}
}

// MockLastVideoRepositoryMockRecorder is the mock recorder for MockLastVideoRepository.
type MockLastVideoRepositoryMockRecorder struct {
	mock *MockLastVideoRepository
}

// NewMockLastVideoRepository creates a new mock instance.
func NewMockLastVideoRepository(ctrl *gomock.Controller) *MockLastVideoRepository {
	mock := &MockLastVideoRepository{ctrl: ctrl}
	mock.recorder = &MockLastVideoRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLastVideoRepository) EXPECT() *MockLastVideoRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLastVideoRepository) Create(ctx context.Context, upload media.LastUpload) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, upload)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLastVideoRepositoryMockRecorder) Create(ctx, upload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLastVideoRepository)(nil).Create), ctx, upload)
}

// GetLastVideo mocks base method.
func (m *MockLastVideoRepository) GetLastVideo(ctx context.Context, user_id string) (media.LastUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastVideo", ctx, user_id)
	ret0, _ := ret[0].(media.LastUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastVideo indicates an expected call of GetLastVideo.
func (mr *MockLastVideoRepositoryMockRecorder) GetLastVideo(ctx, user_id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastVideo", reflect.TypeOf((*MockLastVideoRepository)(nil).GetLastVideo), ctx, user_id)
}
