// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/labib0x9/ffgif/internal/port/processor (interfaces: VideoProcessor)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=mocks/mock_processor.go github.com/labib0x9/ffgif/internal/port/processor VideoProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	processor "github.com/labib0x9/ffgif/internal/port/processor"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoProcessor is a mock of VideoProcessor interface.
type MockVideoProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockVideoProcessorMockRecorder
	isgomock struct{}
}

// MockVideoProcessorMockRecorder is the mock recorder for MockVideoProcessor.
type MockVideoProcessorMockRecorder struct {
	mock *MockVideoProcessor
}

// NewMockVideoProcessor creates a new mock instance.
func NewMockVideoProcessor(ctrl *gomock.Controller) *MockVideoProcessor {
	mock := &MockVideoProcessor{ctrl: ctrl}
	mock.recorder = &MockVideoProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoProcessor) EXPECT() *MockVideoProcessorMockRecorder {
	return m.recorder
}

// PreProcess mocks base method.
func (m *MockVideoProcessor) PreProcess(ctx context.Context, key string) (*processor.PrePrecessedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreProcess", ctx, key)
	ret0, _ := ret[0].(*processor.PrePrecessedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PreProcess indicates an expected call of PreProcess.
func (mr *MockVideoProcessorMockRecorder) PreProcess(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreProcess", reflect.TypeOf((*MockVideoProcessor)(nil).PreProcess), ctx, key)
}

// Process mocks base method.
func (m *MockVideoProcessor) Process(ctx context.Context, JobId, Key string, Start, End float32, Width, FPS int, Loop bool) (*processor.JobResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, JobId, Key, Start, End, Width, FPS, Loop)
	ret0, _ := ret[0].(*processor.JobResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockVideoProcessorMockRecorder) Process(ctx, JobId, Key, Start, End, Width, FPS, Loop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockVideoProcessor)(nil).Process), ctx, JobId, Key, Start, End, Width, FPS, Loop)
}
