// Code generated by MockGen. DO NOT EDIT.
// Source: share.go
//
// Generated by this command:
//
//	mockgen -source=share.go -destination=mocks/mock_share_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	share "github.com/labib0x9/ffgif/internal/domain/share"
	gomock "go.uber.org/mock/gomock"
)

// MockShareRepository is a mock of ShareRepository interface.
type MockShareRepository struct {
	ctrl     *gomock.Controller
	recorder *MockShareRepositoryMockRecorder
	isgomock struct{}
}

// MockShareRepositoryMockRecorder is the mock recorder for MockShareRepository.
type MockShareRepositoryMockRecorder struct {
	mock *MockShareRepository
}

// NewMockShareRepository creates a new mock instance.
func NewMockShareRepository(ctrl *gomock.Controller) *MockShareRepository {
	mock := &MockShareRepository{ctrl: ctrl}
	mock.recorder = &MockShareRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareRepository) EXPECT() *MockShareRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockShareRepository) Create(ctx context.Context, gif share.Share) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, gif)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockShareRepositoryMockRecorder) Create(ctx, gif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockShareRepository)(nil).Create), ctx, gif)
}

// CreateByToken mocks base method.
func (m *MockShareRepository) CreateByToken(ctx context.Context, gif share.ShareByToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateByToken", ctx, gif)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateByToken indicates an expected call of CreateByToken.
func (mr *MockShareRepositoryMockRecorder) CreateByToken(ctx, gif any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateByToken", reflect.TypeOf((*MockShareRepository)(nil).CreateByToken), ctx, gif)
}

// Delete mocks base method.
func (m *MockShareRepository) Delete(ctx context.Context, key, shareWithId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key, shareWithId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockShareRepositoryMockRecorder) Delete(ctx, key, shareWithId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockShareRepository)(nil).Delete), ctx, key, shareWithId)
}

// Get mocks base method.
func (m *MockShareRepository) Get(ctx context.Context, userID string) ([]share.GifResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID)
	ret0, _ := ret[0].([]share.GifResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockShareRepositoryMockRecorder) Get(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockShareRepository)(nil).Get), ctx, userID)
}

// GetByToken mocks base method.
func (m *MockShareRepository) GetByToken(ctx context.Context, token string) (share.GifTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByToken", ctx, token)
	ret0, _ := ret[0].(share.GifTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByToken indicates an expected call of GetByToken.
func (mr *MockShareRepositoryMockRecorder) GetByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByToken", reflect.TypeOf((*MockShareRepository)(nil).GetByToken), ctx, token)
}

// GetOwner mocks base method.
func (m *MockShareRepository) GetOwner(ctx context.Context, user, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwner", ctx, user, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwner indicates an expected call of GetOwner.
func (mr *MockShareRepositoryMockRecorder) GetOwner(ctx, user, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwner", reflect.TypeOf((*MockShareRepository)(nil).GetOwner), ctx, user, key)
}
