package httputil

const (
	VALIDATION_FAILED    = "VALIDATION_FAILED"
	BAD_REQUEST          = "BAD_REQUEST"
	RATE_LIMITED         = "RATE_LIMITED"
	INTERNAL_ERROR       = "INTERNAL_ERROR"
	UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"
	PRECONDITION_FAILED  = "PRECONDITION_FAILED"
)
